version: '3'
services:

  roscore:
    container_name: roscore
    image: thesis
    network_mode: "host"
    restart: always
    command: zsh -c 'source ~/.zshrc && roscore'
    volumes:
      - "./:/home/thesis:rw"
    tty: true
    privileged: true

  terminal:
    depends_on:
      - roscore
    container_name: terminal
    image: thesis
    network_mode: host
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true

  rviz:
    depends_on:
      - roscore
    container_name: rviz
    image: thesis
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && rviz -d /home/thesis/ROS/src/ugv_sim/limo/limo_description/rviz/model_display.rviz'
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    restart: always
    stdin_open: true

  gazebo:
    depends_on:
      - rviz
      - roscore
    container_name: gazebo
    image: thesis
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && cd /home/thesis/ROS && catkin build && roslaunch limo_gazebo_sim limo_ackerman.launch'
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
