#!/bin/bash
xhost +
function install {
	docker build -t thesis .
}

function installnogpu {
	docker build -t thesis -f Dockerfile.nogpu .
}

function start {
	docker compose up -d roscore terminal rvizGPU gazeboGPU
}

function startNoGPU {
	docker compose up -d roscore terminal rvizNOGPU gazeboNOGPU
}
function startNoSim {
	docker compose up -d roscore terminal rvizGPU
}

function terminal {
	docker compose up -d roscore terminal
	docker exec -it terminal /bin/zsh
}

function clean {
    PREFIX=$1
    shift
    if [ -z "$PREFIX" ]
    then
        echo "Please provide a prefix."
        exit 1
    fi
    
    CONTAINERS=$(docker ps -q --filter name=$PREFIX*)
    
    if [ -n "$CONTAINERS" ]; then
        echo "$CONTAINERS" | xargs docker rm -f
    else
        echo "No containers found matching the filter criteria."
    fi
}

function stop {
    docker compose down
    clean thesis
}


function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}
${@:-start}
